###ThymeLeaf配置
spring:
  thymeleaf:
    #prefix：指定模板所在的目录
    prefix: classpath:/static/
    #check-tempate-location: 检查模板路径是否存在
    check-template-location: true
    #cache: 是否缓存，开发模式下设置为false，避免改了模板还要重启服务器，线上设置为true，可以提高性能。
    cache: true
    suffix: .html
    encoding: UTF-8
    mode: HTML5

  mvc:
    hiddenmethod:
      filter:
        enabled: true
  #配置相关信息
  datasource:
    #druid专用配置
    druid:
      driver-class-name: com.mysql.cj.jdbc.Driver
      url: jdbc:mysql://localhost:3306/ssm_db?serverTimezone=UTC
      username: root
      password: 123456
# 通用的配置相关信息
#  datasource:
#    driver-class-name: com.mysql.cj.jdbc.Driver
#    url: jdbc:mysql://localhost:3306/ssm_db?serverTimezone=UTC
#    username: root
#    password: 123456
#    type: com.alibaba.druid.pool.DruidDataSource


server:
  port: 8080

enterprise:
  name: itcast
  age: 16
  tel: 40061840
  subject:
    - Java
    - 前端
    - 大数据

#1.设置Mp相关的配置，加数据库表的前缀  2.也可以在实体类中加注解 如 @TableName("tbl_book")
#mybatis-plus:
#  global-config:
#    db-config:
#      table-prefix: tbl_